# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/vivado/08_CPU_memory_reference/Board.xdc

# IP: D:/vivado/08_CPU_memory_reference/Inst_ROM/Inst_ROM.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Inst_ROM || ORIG_REF_NAME==Inst_ROM} -quiet] -quiet
