# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/vivado/09_CPU_Interrupt/Inst_ROM/Inst_ROM.xci
# IP: The module: 'Inst_ROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/vivado/09_CPU_Interrupt/Inst_ROM/Inst_ROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Inst_ROM'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/vivado/09_CPU_Interrupt/Inst_ROM/Inst_ROM.xci
# IP: The module: 'Inst_ROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/vivado/09_CPU_Interrupt/Inst_ROM/Inst_ROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Inst_ROM'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
