# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param synth.incrementalSynthesisCache C:/Users/Administrator/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-1120-BLUEFLAMELEE/incrSyn
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a100tfgg484-2L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/vivado/06_CPU_Data_Processing/06_CPU_Data_Processing.cache/wt [current_project]
set_property parent.project_path D:/vivado/06_CPU_Data_Processing/06_CPU_Data_Processing.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/vivado/06_CPU_Data_Processing/06_CPU_Data_Processing.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files D:/vivado/06_CPU_Data_Processing/test.coe
read_verilog -library xil_defaultlib {
  D:/vivado/06_CPU_Data_Processing/ALU.v
  D:/vivado/06_CPU_Data_Processing/ALU_Shift.v
  D:/vivado/06_CPU_Data_Processing/CPU.v
  D:/vivado/06_CPU_Data_Processing/Display.v
  D:/vivado/06_CPU_Data_Processing/Inst.v
  D:/vivado/06_CPU_Data_Processing/RegFile.v
  D:/vivado/06_CPU_Data_Processing/Shift.v
  D:/vivado/06_CPU_Data_Processing/board_cpu.v
}
read_ip -quiet D:/vivado/06_CPU_Data_Processing/Inst_ROM/Inst_ROM.xci
set_property used_in_implementation false [get_files -all d:/vivado/06_CPU_Data_Processing/Inst_ROM/Inst_ROM_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/vivado/06_CPU_Data_Processing/Board.xdc
set_property used_in_implementation false [get_files D:/vivado/06_CPU_Data_Processing/Board.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top board_cpu -part xc7a100tfgg484-2L


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef board_cpu.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file board_cpu_utilization_synth.rpt -pb board_cpu_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
