# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/vivado/07_CPU_Branch/Inst_ROM/Inst_ROM.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Inst_ROM || ORIG_REF_NAME==Inst_ROM} -quiet] -quiet
