# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/vivado/08_CPU_memory_reference/08_CPU_memory_reference.srcs/sources_1/ip/Data_RAM/Data_RAM.xci
# IP: The module: 'Data_RAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/vivado/08_CPU_memory_reference/08_CPU_memory_reference.srcs/sources_1/ip/Data_RAM/Data_RAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Data_RAM'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/vivado/08_CPU_memory_reference/08_CPU_memory_reference.srcs/sources_1/ip/Data_RAM/Data_RAM.xci
# IP: The module: 'Data_RAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/vivado/08_CPU_memory_reference/08_CPU_memory_reference.srcs/sources_1/ip/Data_RAM/Data_RAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Data_RAM'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
