# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tfgg484-2L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/vivado/09_CPU_Interrupt/09_CPU_Interrupt.cache/wt [current_project]
set_property parent.project_path D:/vivado/09_CPU_Interrupt/09_CPU_Interrupt.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/vivado/09_CPU_Interrupt/09_CPU_Interrupt.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files D:/vivado/09_CPU_Interrupt/test.coe
add_files D:/vivado/09_CPU_Interrupt/data.coe
read_verilog -library xil_defaultlib {
  D:/vivado/09_CPU_Interrupt/ALU.v
  D:/vivado/09_CPU_Interrupt/ALU_Shift.v
  D:/vivado/09_CPU_Interrupt/CPSR.v
  D:/vivado/09_CPU_Interrupt/Inst.v
  D:/vivado/09_CPU_Interrupt/RegFile.v
  D:/vivado/09_CPU_Interrupt/Shift.v
  D:/vivado/09_CPU_Interrupt/Stack.v
  D:/vivado/09_CPU_Interrupt/request.v
  D:/vivado/09_CPU_Interrupt/CPU.v
}
read_ip -quiet D:/vivado/09_CPU_Interrupt/Data_RAM/Data_RAM.xci
set_property used_in_implementation false [get_files -all d:/vivado/09_CPU_Interrupt/Data_RAM/Data_RAM_ooc.xdc]

read_ip -quiet D:/vivado/09_CPU_Interrupt/Inst_ROM/Inst_ROM.xci
set_property used_in_implementation false [get_files -all d:/vivado/09_CPU_Interrupt/Inst_ROM/Inst_ROM_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/vivado/09_CPU_Interrupt/Board.xdc
set_property used_in_implementation false [get_files D:/vivado/09_CPU_Interrupt/Board.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top CPU -part xc7a100tfgg484-2L


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef CPU.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file CPU_utilization_synth.rpt -pb CPU_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
