# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/vivado/03_ALU/03_ALU.srcs/sources_1/ip/ALU_Shift_0/ALU_Shift_0.xci
# IP: The module: 'ALU_Shift_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/vivado/03_ALU/03_ALU.srcs/sources_1/ip/ALU_Shift_0/src/Board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ALU_Shift_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/vivado/03_ALU/03_ALU.srcs/sources_1/ip/ALU_Shift_0/ALU_Shift_0.xci
# IP: The module: 'ALU_Shift_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/vivado/03_ALU/03_ALU.srcs/sources_1/ip/ALU_Shift_0/src/Board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ALU_Shift_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
